services:
  fsl-db:
    image: postgres:16
    environment:
      POSTGRES_DB: fsl
      POSTGRES_USER: fsl
      POSTGRES_PASSWORD: fsl
    ports:
      - "5432:5432"
    volumes:
      - fsl-db-data:/var/lib/postgresql/data

volumes:
  fsl-db-data:
